server:
  port: 9995

spring:
  application:
    name: test

logging:
  file: application.log
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/